version: "3.6"
services:
  postgres:
    container_name: databas
    hostname: databas
    image: postgres
    restart: always
    volumes:
      - ../database/db:/var/lib/postgresql/data/
      - ../database/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PORT_POSTGRES}:5432"
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:latest
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    ports:
      - "${PORT_HASURA}:8080"
  auth:
    container_name: auth
    image: nhost/hasura-auth:latest
    depends_on:
      - postgres
      - hasura
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_GRAPHQL_URL: ${HASURA_GRAPHQL_GRAPHQL_URL}
      AUTH_SMTP_HOST: ${AUTH_SMTP_HOST}
      AUTH_SMTP_PORT: ${PORT_SMTP}
      AUTH_SMTP_USER: ${AUTH_SMTP_USER}
      AUTH_SMTP_PASS: ${AUTH_SMTP_PASS}
      AUTH_SMTP_SENDER: ${AUTH_SMTP_SENDER}
      AUTH_SMTP_SECURE: ${AUTH_SMTP_SECURE}
      AUTH_SMTP_AUTH_METHOD: ${AUTH_SMTP_AUTH_METHOD}
      AUTH_WEBAUTHN_ENABLED: true
      AUTH_WEBAUTHN_RP_NAME: "Nhost App"
    ports:
      - "${PORT_AUTH}:4000"
    volumes:
      - ../auth/email-templates:/app/email-templates
  mailhog:
    container_name: auth_mailserver
    image: mailhog/mailhog
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: ${PORT_SMTP}
      SMTP_PASS: ${AUTH_SMTP_PASS}
      SMTP_USER: ${AUTH_SMTP_USER}
      SMTP_SECURE: "${AUTH_SMTP_SECURE}"
      SMTP_SENDER: ${AUTH_SMTP_SENDER}
    ports:
      - ${PORT_SMTP}:1025 # smtp server
      - ${PORT_MAIL_UI}:8025 # web ui
    volumes:
      - ../auth/mailhog:/maildir
  web:
    container_name: frontend
    image: nginx
    ports:
      - ${PORT_FRONTEND}:80
    volumes:
      - ${FRONTEND_PATH}:/usr/share/nginx/html
